[package]
name = "voxel-rs-common"
version = "0.1.0"
authors = ["Technici4n", "Azercoco"]
edition = "2018"

[dependencies]
# Utilities
anyhow = "1.0"
log = "0.4"
ron = "0.5"
serde = "1.0"

# Image loading
image = "0.22"
texture_packer = "0.17"

# Math
nalgebra = "0.18"